### ISSUE TITLE
Does this work? or is it WIP?

### ISSUE THREAD

**Issue by 3deep5me** [sp-yduck/cluster-api-provider-proxmox#1]
HI, i'm interested in your work.
Is it at the moment WIP or can i give it a try 😊?

**Comment by sp-yduck** [comment]
oh thank you for comment. currently it's WIP.

**Comment by sp-yduck** [comment]
Hi, @3deep5me 
I just made a very first release of this project. Still there are many future works but now you can give it a try 🎉 !
[Here](https://github.com/sp-yduck/cluster-api-provider-proxmox#quick-start) is quick start guides.
Thank you for being interested of this project. Let me close for now. 😄

**Comment by 3deep5me** [comment]
Hi, amazing! 
I will try it out this weekend. 
Just had a look at the sample config files. Nice so far!
