### ISSUE TITLE
Provide a solultion for control plane load balancer

### ISSUE THREAD

**Issue by sp-yduck** [sp-yduck/cluster-api-provider-proxmox#2]
When provisioning a cluster, infraCluster controller should reconcile a load balancer for control plane. since cluster-api-provider-proxmox does not rely on specific cloud provider load balancer, it should provide something self-hosted load balancer and allow configuration of an external load balancer post-install if desired.

**Comment by 3deep5me** [comment]
I would say this is something you could do with kube-vip. But I do not know if it's cluster-api conform do add this into the provider. 

Another way is Cilium CNI which can do BGB-LB for control plane, but this would be out of scope of the provider I think. (Normally CNI is a user decision as far as I know)

Any thoughts?

**Comment by sp-yduck** [comment]
yes CNI should be out of scope as [official doc](https://cluster-api.sigs.k8s.io/developer/architecture/controllers/control-plane.html?highlight=coredns#control-plane-provider) explicitly says it's **prohibited service**.

one of the major candidate in my mind is haproxy as same way as [cluster-api-provider-vshpere](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere#haproxy-published-ovas) is doing.

**Comment by 3deep5me** [comment]
👍 It would be nice if there was then the possibility to disable the Ha proxy, e.g. if someone wants to use another lb provider.

**Comment by sp-yduck** [comment]
Confirmed kube-vip works fine as ha control-plane solution without any source updates. Just updated tempalte manifest with kube-vip : https://github.com/sp-yduck/cluster-api-provider-proxmox/commit/006acd9819156fcf6320185f7f42463ba3ac13ea
will close the issue. we might think other solution in the future according to needs etc. .
