### ISSUE TITLE
Consider Acronyms for cluster-api-provider-proxmox

### ISSUE THREAD

**Issue by sp-yduck** [sp-yduck/cluster-api-provider-proxmox#23]
Acronyms : https://cluster-api.sigs.k8s.io/developer/providers/implementers-guide/naming.html?highlight=acron#a-note-on-acronyms

it seems CAPP is already ocupied by cluster-api-provider-packet according to [this page](https://cluster-api.sigs.k8s.io/clusterctl/provider-contract.html#labels). so we should use another acronyms.

candidates in my mind
- CAPPR (**PR**oxmox)
- CAPPX (**P**roxmo**X**)
- CAPPV (**P**roxmox **V**irtual environment)
- CAPPVE (**P**roxmox **V**irtual **E**nvironment)

**Comment by sp-yduck** [comment]
I personaly like CAPPX though.

**Comment by 3deep5me** [comment]
Would suggest the same! CAPPX sound and looks good!
