### ISSUE TITLE
Consider whether CAPPX should provide LXC instance not only qemu

### ISSUE THREAD

**Issue by sp-yduck** [sp-yduck/cluster-api-provider-proxmox#3]
1. not sure if LXC can be a kubernets node
2. what is the benefit of LXC comparing qemu ?

**Comment by 3deep5me** [comment]
It can be done, but I am personally not a fan of it.(Feels hacky) 
For reference:
https://gist.github.com/triangletodd/02f595cd4c0dc9aac5f7763ca2264185

**Comment by sp-yduck** [comment]
I think we can focus on vm ATM
