### ISSUE TITLE
Error: failed to get provider components for the "proxmox:v0.2.2" provider: failed to apply image overrides: failed to fix containers in deployment cluster-api-provider-proxmox-controller-manager: failed to fix containers: failed to fix image for container manager: couldn't parse image name: repository name must be canonical

### ISSUE THREAD

**Issue by rootjog** [sp-yduck/cluster-api-provider-proxmox#44]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Created cluster using KIND.
``` kind create cluster ```
Then i follow the guide in readme.md.
```  clusterctl init  --config https://raw.githubusercontent.com/sp-yduck/cluster-api-provider-proxmox/main/clusterctl.yaml --infrastructure proxmox:v0.2.2 ```
But got an error:
```
Error: failed to get provider components for the "proxmox:v0.2.2" provider: failed to apply image overrides: failed to fix containers in deployment cluster-api-provider-proxmox-controller-manager: failed to fix containers: failed to fix image for container manager: couldn't parse image name: repository name must be canonical
```

**What did you expect to happen:**
Succesful log, but got an error

```
❯ clusterctl init  --config https://raw.githubusercontent.com/sp-yduck/cluster-api-provider-proxmox/main/clusterctl.yaml --infrastructure proxmox:v0.2.2 -v 3
Fetching providers
Error: failed to get provider components for the "proxmox:v0.2.2" provider: failed to apply image overrides: failed to fix containers in deployment cluster-api-provider-proxmox-controller-manager: failed to fix containers: failed to fix image for container manager: couldn't parse image name: repository name must be canonical
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-proxmox version:  
v0.2.2.

- Proxmox VE version: 
Not needed in this issue.

- Kubernetes version: (use `kubectl version`): 
Client Version: v1.27.4
Kustomize Version: v5.0.1
Server Version: v1.24.15

- OS (e.g. from `/etc/os-release`): 
Debian GNU/Linux

**Comment by rootjog** [comment]
Similar issue here:
https://github.com/kubernetes-sigs/cluster-api-provider-packet/pull/185/commits/af6256a9790f7e7605175e7c66640cd51e04d667

**Comment by sp-yduck** [comment]
FYI: forgot to update release after this commit is merged https://github.com/sp-yduck/cluster-api-provider-proxmox/pull/42/commits/dd2bd3da077b1a3194b7567357e2bf9c418c85fd

**Comment by rootjog** [comment]
Fixed now for me, thanks!
