### ISSUE TITLE
Support multi node proxmox cluster

### ISSUE THREAD

**Issue by sp-yduck** [sp-yduck/cluster-api-provider-proxmox#6]
current CAPPX supports only single node proxmox cluster.
should support multi node proxmox cluster as well.

**Comment by 3deep5me** [comment]
Do you have any ideas so far?
My first thoughts would be to use this endpoint https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/status to get cpu/ram and implement a "scheduler" which decides where to place the node.
Maybe we could introduce a field called `nodeName` in ProxmoxMachine similar to the default Pod resource. https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#scheduling

If it`s not set the scheduler decides. 

That's just an easy idea i`m aware that it may comes more difficult or require more refactoring.

**Comment by 3deep5me** [comment]
I do not know if its allowed to introduce new fields in a cluster-api-provider. If not i think failureDomain could be used for that not perfect but in fact if you have a proxmox-cluster without HA one node is a kind of a failureDomain. 😅

But personally i would like to use (warning: big thinking) failureDomain as an abstraction for a whole proxmox-cluster so it would be theoretically possible to stretch a kubernetes-cluster over many proxmox-clusters aka. multi-cloud use-cases or just real AZs which are in different physical locations.
