### ISSUE TITLE
MachineDeployment sample for quick start

### ISSUE THREAD

**Issue by sp-yduck** [sp-yduck/cluster-api-provider-proxmox#8]
current quick start does not uses MD. should provide a sample for how to use MD.

**Comment by 3deep5me** [comment]
If I get it to run, I would take this as a first issue :)

**Comment by 3deep5me** [comment]
I`m on it 😊.

**Comment by 3deep5me** [comment]
grrr... @sp-yduck 
to use the MachineDeployment it seems like that there is the requirement that the machinetemplate needs a template spec.
See this error:
```
  Warning  ReconcileError  36s (x3 over 77s)    machineset-controller  failed to sync MachineSet replicas: failed to clone infrastructure machine from ProxmoxMachine worker while creating a machine: missing Spec.Template on infrastructure.cluster.x-k8s.io/v1beta1, Kind=ProxmoxMachine "worker"
```
I will try to look into the code and try to fix it. But i`m a go newbee so no e for guarantee for a fix. 😅
