### ISSUE TITLE
Specifying vmID in `ProxmoxMachineTemplate` does not work

### ISSUE THREAD

**Issue by simplysoft** [sp-yduck/cluster-api-provider-proxmox#84]
When using `vmID` in a template, it will be used for each instance of the template, and thus all machines will use that vmID causing various problems (corrupt disks, etc.)

The expectation would be that `vmID` is some kind of starting vmID or base vmID where all other vmID will be based on. 
One strategy could be to use  `max(vmID of all ProxmoxMachine for that template) + 1` and then check if this vmID is still available, and if not, increment further until a free vmID is found

**Comment by sp-yduck** [comment]
yes you right. but it's same as `providerID`. both of `providerID` and `vmID` are unique for each `ProxmoxMachine`. so basically `vmID` should not be specified in `ProxmoxMachineTemplate` as same as `providerID`.
if we would like to have something to specify vmid range, we should introduce another field in my opinion.
